version: '3.8'
services:
  app:
    entrypoint: [bin/entry]
    build: .
    volumes:
      - .:/app:rw
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    tty: true
    ports:
      - 3300:3000
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    image: mysql:8.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: notes_backend_development
    ports:
      - "3307:3306"
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
